var pickerJson = [
  { name: "不限", pinyin: "Buxian", cities: [{ name: "不限", pinyin: "Buxian" }], 'hidden': true },{ name: "北京", pinyin: "Beijing", cities: [{ name: "北京", pinyin: "Beijing" }], 'hidden': true },
  { name: "天津", pinyin: "Tianjin", cities: [{ name: "天津", pinyin: "Tianjin" }], 'hidden': true },
  { name: "河北", pinyin: "Hebei", cities: [{ name: "石家庄", pinyin: "Shijiazhuang" }, { name: "秦皇岛", pinyin: "Qinghuangdao" }, { name: "廊坊", pinyin: "Langfang" }, { name: "保定", pinyin: "Baoding" }, { name: "邯郸", pinyin: "Handan" }, { name: "唐山", pinyin: "Tangshan" }, { name: "邢台", pinyin: "Xingtai" }, { name: "衡水", pinyin: "Hengshui" }, { name: "张家口", pinyin: "Zhangjiakou" }, { name: "承德", pinyin: "Chengdei" }, { name: "沧州", pinyin: "Cangzhou" }], 'hidden': true },
  { name: "山西", pinyin: "Shanxi", cities: [{ name: "太原", pinyin: "Taiyuan" }, { name: "大同", pinyin: "Datong" }, { name: "长治", pinyin: "Changzhi" }, { name: "晋中", pinyin: "Jinzhong" }, { name: "阳泉", pinyin: "Yangquan" }, { name: "朔州", pinyin: "Suozhou" }, { name: "运城", pinyin: "Yuncheng" }, { name: "临汾", pinyin: "Linfen" }], 'hidden': true },
  { name: "内蒙古", pinyin: "Neimenggu", cities: [{ name: "呼和浩特", pinyin: "Huhehaote" }, { name: "赤峰", pinyin: "Chifeng" }, { name: "通辽", pinyin: "Tongliao" }, { name: "锡林郭勒", pinyin: "Xilinguole" }, { name: "兴安", pinyin: "Xingan" }], 'hidden': true },
  { name: "辽宁", pinyin: "Liaoning", cities: [{ name: "大连", pinyin: "Dalian" }, { name: "沈阳", pinyin: "Shengyang" }, { name: "鞍山", pinyin: "Anshan" }, { name: "抚顺", pinyin: "Fushun" }, { name: "营口", pinyin: "Yingkou" }, { name: "锦州", pinyin: "Jingzhou" }, { name: "丹东", pinyin: "Dandong" }, { name: "朝阳", pinyin: "Zhaoyang" }, { name: "辽阳", pinyin: "Liaoyang" }, { name: "阜新", pinyin: "Fuxin" }, { name: "铁岭", pinyin: "Tieling" }, { name: "盘锦", pinyin: "Panjin" }, { name: "本溪", pinyin: "Benxi" }, { name: "葫芦岛", pinyin: "Huludao" }], 'hidden': true },
  { name: "吉林", pinyin: "Jilin", cities: [{ name: "长春", pinyin: "Changchun" }, { name: "吉林", pinyin: "Jilin" }, { name: "四平", pinyin: "Siping" }, { name: "辽源", pinyin: "Liaoyuan" }, { name: "通化", pinyin: "Tonghua" }, { name: "延吉", pinyin: "Yanji" }, { name: "白城", pinyin: "Baicheng" }, { name: "辽源", pinyin: "Liaoyuan" }, { name: "松原", pinyin: "Songyuan" }, { name: "临江", pinyin: "Linjiang" }, { name: "珲春", pinyin: "Hunchun" }], 'hidden': true },
  { name: "黑龙江", pinyin: "Heilongjiang", cities: [{ name: "哈尔滨", pinyin: "Haerbin" }, { name: "齐齐哈尔", pinyin: "Qiqihaer" }, { name: "大庆", pinyin: "Daqing" }, { name: "牡丹江", pinyin: "Mudanjiang" }, { name: "鹤岗", pinyin: "Hegang" }, { name: "佳木斯", pinyin: "Jiamusi" }, { name: "绥化", pinyin: "Suihua" }], 'hidden': true },
  { name: "上海", pinyin: "Shanghai", cities: [{ name: "浦东", pinyin: "Pudong" }, { name: "杨浦", pinyin: "Yangpu" }, { name: "徐汇", pinyin: "Xuhui" }, { name: "静安", pinyin: "Jingan" }, { name: "卢湾", pinyin: "Luwan" }, { name: "黄浦", pinyin: "Huangpu" }, { name: "普陀", pinyin: "Putuo" }, { name: "闸北", pinyin: "Zhabei" }, { name: "虹口", pinyin: "Hongkou" }, { name: "长宁", pinyin: "Changning" }, { name: "宝山", pinyin: "Baoshan" }, { name: "闵行", pinyin: "Minhang" }, { name: "嘉定", pinyin: "Jiading" }, { name: "金山", pinyin: "Jinshan" }, { name: "松江", pinyin: "Songjiang" }, { name: "青浦", pinyin: "Qingpu" }, { name: "崇明", pinyin: "Chongming" }, { name: "奉贤", pinyin: "Fengxian" }, { name: "南汇", pinyin: "Nanhui" }], 'hidden': true },
  { name: "江苏", pinyin: "Jiangsu", cities: [{ name: "南京", pinyin: "Nanjing" }, { name: "苏州", pinyin: "Suzhou" }, { name: "无锡", pinyin: "Wuxi" }, { name: "常州", pinyin: "Changzhou" }, { name: "扬州", pinyin: "Yangzhou" }, { name: "徐州", pinyin: "Xuzhou" }, { name: "南通", pinyin: "Nantong" }, { name: "镇江", pinyin: "Zhenjiang" }, { name: "泰州", pinyin: "Taizhou" }, { name: "淮安", pinyin: "Huaian" }, { name: "连云港", pinyin: "Lianyungang" }, { name: "宿迁", pinyin: "Suqian" }, { name: "盐城", pinyin: "Yancheng" }, { name: "淮阴", pinyin: "Huaiyin" }, { name: "沐阳", pinyin: "Muyang" }, { name: "张家港", pinyin: "Zhangjiagang" }], 'hidden': true },
  { name: "浙江", pinyin: "Zhejiang", cities: [{ name: "杭州", pinyin: "Hangzhou" }, { name: "金华", pinyin: "Jinhua" }, { name: "宁波", pinyin: "Ningbo" }, { name: "温州", pinyin: "Wenzhou" }, { name: "嘉兴", pinyin: "Jiaxing" }, { name: "绍兴", pinyin: "Shaoxing" }, { name: "丽水", pinyin: "Lishui" }, { name: "湖州", pinyin: "Huzhou" }, { name: "台州", pinyin: "Taizhou" }, { name: "舟山", pinyin: "Zhoushan" }, { name: "衢州", pinyin: "Quzhou" }], 'hidden': true },
  { name: "安徽", pinyin: "Anhui", cities: [{ name: "合肥", pinyin: "Hefei" }, { name: "马鞍山", pinyin: "Maanshan" }, { name: "蚌埠", pinyin: "Bangbu" }, { name: "黄山", pinyin: "Huangshan" }, { name: "芜湖", pinyin: "Wuhu" }, { name: "淮南", pinyin: "Huainan" }, { name: "铜陵", pinyin: "Tongling" }, { name: "阜阳", pinyin: "Fuyang" }, { name: "宣城", pinyin: "Xuancheng" }, { name: "安庆", pinyin: "Anqing" }], 'hidden': true },
  { name: "福建", pinyin: "Fujian", cities: [{ name: "福州", pinyin: "Fuzhou" }, { name: "厦门", pinyin: "Xiamen" }, { name: "泉州", pinyin: "Quanzhou" }, { name: "漳州", pinyin: "Zhangzhou" }, { name: "南平", pinyin: "Nanping" }, { name: "龙岩", pinyin: "Longyan" }, { name: "莆田", pinyin: "Putian" }, { name: "三明", pinyin: "Sanming" }, { name: "宁德", pinyin: "Ningde" }], 'hidden': true },
  { name: "江西", pinyin: "Jiangxi", cities: [{ name: "南昌", pinyin: "Nanchang" }, { name: "景德镇", pinyin: "Jingdezhen" }, { name: "上饶", pinyin: "Shangrao" }, { name: "萍乡", pinyin: "Pingxiang" }, { name: "九江", pinyin: "Jiujiang" }, { name: "吉安", pinyin: "Jian" }, { name: "宜春", pinyin: "Xuanchun" }, { name: "鹰潭", pinyin: "Yingtan" }, { name: "新余", pinyin: "Xinyu" }, { name: "赣州", pinyin: "Ganzhou" }], 'hidden': true },
  { name: "山东", pinyin: "Shandong", cities: [{ name: "青岛", pinyin: "Qingdao" }, { name: "济南", pinyin: "Jinan" }, { name: "淄博", pinyin: "Zibo" }, { name: "烟台", pinyin: "Yantai" }, { name: "泰安", pinyin: "Taian" }, { name: "临沂", pinyin: "Linyi" }, { name: "日照", pinyin: "Rizhao" }, { name: "德州", pinyin: "Dezhou" }, { name: "威海", pinyin: "Weihai" }, { name: "东营", pinyin: "Dongying" }, { name: "荷泽", pinyin: "Heze" }, { name: "济宁", pinyin: "Jining" }, { name: "潍坊", pinyin: "Weifang" }, { name: "枣庄", pinyin: "Zaozhuang" }, { name: "聊城", pinyin: "Liaocheng" }], 'hidden': true },
  { name: "河南", pinyin: "Henan", cities: [{ name: "郑州", pinyin: "Zhengzhou" }, { name: "洛阳", pinyin: "Luoyang" }, { name: "开封", pinyin: "Kaifeng" }, { name: "平顶山", pinyin: "Pingdingshan" }, { name: "濮阳", pinyin: "Puyang" }, { name: "安阳", pinyin: "Anyang" }, { name: "许昌", pinyin: "Xuchang" }, { name: "南阳", pinyin: "Nanyang" }, { name: "信阳", pinyin: "Xinyang" }, { name: "周口", pinyin: "Zhoukou" }, { name: "新乡", pinyin: "Xinxiang" }, { name: "焦作", pinyin: "Jiaozuo" }, { name: "三门峡", pinyin: "Sanmenxia" }, { name: "商丘", pinyin: "Shangqiu" }], 'hidden': true },
  { name: "湖北", pinyin: "Hubei", cities: [{ name: "武汉", pinyin: "Wuhan" }, { name: "襄樊", pinyin: "Xiangfan" }, { name: "孝感", pinyin: "Xiaogan" }, { name: "十堰", pinyin: "Shiyan" }, { name: "荆州", pinyin: "Jingzhou" }, { name: "黄石", pinyin: "Huangshi" }, { name: "宜昌", pinyin: "Yichang" }, { name: "黄冈", pinyin: "Huanggang" }, { name: "恩施", pinyin: "Enshi" }, { name: "鄂州", pinyin: "Ezhou" }, { name: "江汉", pinyin: "Jianghan" }, { name: "随枣", pinyin: "Suizao" }, { name: "荆沙", pinyin: "Jingsha" }, { name: "咸宁", pinyin: "Weining" }], 'hidden': true },
  { name: "湖南", pinyin: "Hunan", cities: [{ name: "长沙", pinyin: "Changsha" }, { name: "湘潭", pinyin: "Xiangtan" }, { name: "岳阳", pinyin: "Yueyang" }, { name: "株洲", pinyin: "Zhuzhou" }, { name: "怀化", pinyin: "Huaihua" }, { name: "永州", pinyin: "Yongzhou" }, { name: "益阳", pinyin: "Yiyang" }, { name: "张家界", pinyin: "Zhangjiajie" }, { name: "常德", pinyin: "Changde" }, { name: "衡阳", pinyin: "Hengyang" }, { name: "湘西", pinyin: "Xiangxi" }, { name: "邵阳", pinyin: "Shaoyang" }, { name: "娄底", pinyin: "Loudi" }, { name: "郴州", pinyin: "Chenzhou" }], 'hidden': true },
  { name: "广东", pinyin: "Guangdong", cities: [{ name: "广州", pinyin: "Guangzhou" }, { name: "深圳", pinyin: "Shenzhen" }, { name: "东莞", pinyin: "Dongguan" }, { name: "佛山", pinyin: "Fushan" }, { name: "珠海", pinyin: "Zhuhai" }, { name: "汕头", pinyin: "Shantou" }, { name: "韶关", pinyin: "Shaoguan" }, { name: "江门", pinyin: "Jiangmen" }, { name: "梅州", pinyin: "Meizhou" }, { name: "揭阳", pinyin: "Jieyang" }, { name: "中山", pinyin: "Zhongshan" }, { name: "河源", pinyin: "Heyuan" }, { name: "惠州", pinyin: "Huizhou" }, { name: "茂名", pinyin: "Maoming" }, { name: "湛江", pinyin: "Zhanjiang" }, { name: "阳江", pinyin: "Yangjiang" }, { name: "潮州", pinyin: "Chaozhou" }, { name: "云浮", pinyin: "Yunfu" }, { name: "汕尾", pinyin: "Shanwei" }, { name: "潮阳", pinyin: "Chaoyang" }, { name: "肇庆", pinyin: "Zhaoqing" }, { name: "顺德", pinyin: "Shunde" }, { name: "清远", pinyin: "Qingyuan" }], 'hidden': true },
  { name: "广西", pinyin: "Guangxi", cities: [{ name: "南宁", pinyin: "Nanning" }, { name: "桂林", pinyin: "Guilin" }, { name: "柳州", pinyin: "Liuzhou" }, { name: "梧州", pinyin: "Wuzhou" }, { name: "来宾", pinyin: "Laibin" }, { name: "贵港", pinyin: "Guigang" }, { name: "玉林", pinyin: "Yulin" }, { name: "贺州", pinyin: "Hezhou" }], 'hidden': true },
  { name: "海南", pinyin: "Hainan", cities: [{ name: "海口", pinyin: "Haikou" }, { name: "三亚", pinyin: "Sanya" }], 'hidden': true },
  { name: "重庆", pinyin: "Chongqing", cities: [{ name: "重庆市", pinyin: "Chongqing" }], 'hidden': true },
  { name: "四川", pinyin: "Sichuan", cities: [{ name: "成都", pinyin: "Chengdu" }, { name: "达州", pinyin: "Dazhou" }, { name: "南充", pinyin: "Nanchong" }, { name: "乐山", pinyin: "Leshan" }, { name: "绵阳", pinyin: "Mianyang" }, { name: "德阳", pinyin: "Deyang" }, { name: "内江", pinyin: "Neijiang" }, { name: "遂宁", pinyin: "Suining" }, { name: "宜宾", pinyin: "Yibin" }, { name: "巴中", pinyin: "Bazhong" }, { name: "自贡", pinyin: "Zigong" }, { name: "康定", pinyin: "Kangding" }, { name: "攀枝花", pinyin: "Panzhihua" }], 'hidden': true },
  { name: "贵州", pinyin: "Guizhou", cities: [{ name: "贵阳", pinyin: "Guiyang" }, { name: "遵义", pinyin: "Zunyi" }, { name: "安顺", pinyin: "Anshun" }, { name: "黔西南", pinyin: "Qianxinan" }, { name: "都匀", pinyin: "Douyun" }], 'hidden': true },
  { name: "云南", pinyin: "Yunnan", cities: [{ name: "昆明", pinyin: "Kunming" }, { name: "丽江", pinyin: "Lijiang" }, { name: "昭通", pinyin: "Zhaotong" }, { name: "玉溪", pinyin: "Yuxi" }, { name: "临沧", pinyin: "Lincang" }, { name: "文山", pinyin: "Wenshan" }, { name: "红河", pinyin: "Honghe" }, { name: "楚雄", pinyin: "Chuxiong" }, { name: "大理", pinyin: "Dali" }], 'hidden': true },
  { name: "西藏", pinyin: "Xizang", cities: [{ name: "拉萨", pinyin: "Lasa" }, { name: "林芝", pinyin: "Linzhi" }, { name: "日喀则", pinyin: "Rikaze" }, { name: "昌都", pinyin: "Changdou" }], 'hidden': true },
  { name: "陕西", pinyin: "Shaanxi", cities: [{ name: "西安", pinyin: "Xian" }, { name: "咸阳", pinyin: "Xianyang" }, { name: "延安", pinyin: "Yanan" }, { name: "汉中", pinyin: "Hanzhong" }, { name: "榆林", pinyin: "Yulin" }, { name: "商南", pinyin: "Shangnan" }, { name: "略阳", pinyin: "Lueyang" }, { name: "宜君", pinyin: "Yijun" }, { name: "麟游", pinyin: "Qiyou" }, { name: "白河", pinyin: "Baihe" }], 'hidden': true },
  { name: "甘肃", pinyin: "Gansu", cities: [{ name: "兰州", pinyin: "Lanzhou" }, { name: "金昌", pinyin: "Jinchang" }, { name: "天水", pinyin: "Tianshui" }, { name: "武威", pinyin: "Wuwei" }, { name: "张掖", pinyin: "Zhangye" }, { name: "平凉", pinyin: "Pingliang" }, { name: "酒泉", pinyin: "Jiuquan" }], 'hidden': true },
  { name: "青海", pinyin: "Qinghai", cities: [{ name: "黄南", pinyin: "Huangnan" }, { name: "海南", pinyin: "Hainan" }, { name: "西宁", pinyin: "Xining" }, { name: "海东", pinyin: "Haidong" }, { name: "海西", pinyin: "Haixi" }, { name: "海北", pinyin: "Haibei" }, { name: "果洛", pinyin: "Guoluo" }, { name: "玉树", pinyin: "Yushu" }], 'hidden': true },
  { name: "宁夏", pinyin: "Ningxia", cities: [{ name: "银川", pinyin: "Yinchuan" }, { name: "吴忠", pinyin: "Wuzhong" }], 'hidden': true },
  { name: "新疆", pinyin: "Xinjiang", cities: [{ name: "乌鲁木齐", pinyin: "Wulumuqi" }, { name: "哈密", pinyin: "Hami" }, { name: "喀什", pinyin: "Kashi" }, { name: "巴音郭楞", pinyin: "Bayinguoleng" }, { name: "昌吉", pinyin: "Changji" }, { name: "伊犁", pinyin: "Yili" }, { name: "阿勒泰", pinyin: "Aletai" }, { name: "克拉玛依", pinyin: "Kelamayi" }, { name: "博尔塔拉", pinyin: "Boertala" }], 'hidden': true },
  { name: "香港", cities: [{ name: "香港", pinyin: "Xianggang" }], 'hidden': true },
  { name: "澳门", cities: [{ name: "澳门", pinyin: "Aomen" }], 'hidden': true }
]
var geolocation = [
  ["AO", "安哥拉"],
  ["AF", "阿富汗"],
  ["AL", "阿爾巴尼亞"],
  ["DZ", "阿爾及利亞"],
  ["AD", "安道爾共和國"],
  ["AI", "安圭拉島"],
  ["AG", "安提瓜和巴布達"],
  ["AR", "阿根廷"],
  ["AM", "亞美尼亞"],
  ["AU", "澳大利亞"],
  ["AT", "奧地利"],
  ["AZ", "阿塞拜疆"],
  ["BS", "巴哈馬"],
  ["BH", "巴林"],
  ["BD", "孟加拉國"],
  ["BB", "巴巴多斯"],
  ["BY", "白俄羅斯"],
  ["BE", "比利時"],
  ["BZ", "伯利茲"],
  ["BJ", "貝寧"],
  ["BM", "百慕大群島"],
  ["BO", "玻利維亞"],
  ["BW", "博茨瓦納"],
  ["BR", "巴西"],
  ["BN", "文萊"],
  ["BG", "保加利亞"],
  ["BF", "布基納法索"],
  ["MM", "緬甸"],
  ["BI", "布隆迪"],
  ["CM", "喀麥隆"],
  ["CA", "加拿大"],
  ["CF", "中非共和國"],
  ["TD", "乍得"],
  ["CL", "智利"],
  ["CN", "中國"],
  ["CO", "哥倫比亞"],
  ["CG", "剛果"],
  ["CK", "庫克群島"],
  ["CR", "哥斯達黎加"],
  ["CU", "古巴"],
  ["CY", "塞浦路斯"],
  ["CZ", "捷克"],
  ["DK", "丹麥"],
  ["DJ", "吉布提"],
  ["DO", "多米尼加共和國"],
  ["EC", "厄瓜多爾"],
  ["EG", "埃及"],
  ["SV", "薩爾瓦多"],
  ["EE", "愛沙尼亞"],
  ["ET", "埃塞俄比亞"],
  ["FJ", "斐濟"],
  ["FI", "芬蘭"],
  ["FR", "法國"],
  ["GF", "法屬圭亞那"],
  ["GA", "加蓬"],
  ["GM", "岡比亞"],
  ["GE", "格魯吉亞"],
  ["DE", "德國"],
  ["GH", "加納"],
  ["GI", "直布羅陀"],
  ["GR", "希臘"],
  ["GD", "格林納達"],
  ["GU", "關島"],
  ["GT", "危地馬拉"],
  ["GN", "幾內亞"],
  ["GY", "圭亞那"],
  ["HT", "海地"],
  ["HN", "洪都拉斯"],
  ["HK", "香港"],
  ["HU", "匈牙利"],
  ["IS", "冰島"],
  ["IN", "印度"],
  ["ID", "印度尼西亞"],
  ["IR", "伊朗"],
  ["IQ", "伊拉克"],
  ["IE", "愛爾蘭"],
  ["IL", "以色列"],
  ["IT", "意大利"],
  ["JM", "牙買加"],
  ["JP", "日本"],
  ["JO", "約旦"],
  ["KH", "柬埔寨"],
  ["KZ", "哈薩克斯坦"],
  ["KE", "肯尼亞"],
  ["KR", "韓國"],
  ["KW", "科威特"],
  ["KG", "吉爾吉斯坦"],
  ["LA", "老撾"],
  ["LV", "拉脫維亞"],
  ["LB", "黎巴嫩"],
  ["LS", "萊索托"],
  ["LR", "利比里亞"],
  ["LY", "利比亞"],
  ["LI", "列支敦士登"],
  ["LT", "立陶宛"],
  ["LU", "盧森堡"],
  ["MO", "澳門"],
  ["MG", "馬達加斯加"],
  ["MW", "馬拉維"],
  ["MY", "馬來西亞"],
  ["MV", "馬爾代夫"],
  ["ML", "馬里"],
  ["MT", "馬耳他"],
  ["MU", "毛里求斯"],
  ["MX", "墨西哥"],
  ["MD", "摩爾多瓦"],
  ["MC", "摩納哥"],
  ["MN", "蒙古"],
  ["MS", "蒙特塞拉特島"],
  ["MA", "摩洛哥"],
  ["MZ", "莫桑比克"],
  ["NA", "納米比亞"],
  ["NR", "瑙魯"],
  ["NP", "尼泊爾"],
  ["NL", "荷蘭"],
  ["NZ", "新西蘭"],
  ["NI", "尼加拉瓜"],
  ["NE", "尼日爾"],
  ["NG", "尼日利亞"],
  ["KP", "朝鮮"],
  ["NO", "挪威"],
  ["OM", "阿曼"],
  ["PK", "巴基斯坦"],
  ["PA", "巴拿馬"],
  ["PG", "巴布亞新幾內亞"],
  ["PY", "巴拉圭"],
  ["PE", "秘魯"],
  ["PH", "菲律賓"],
  ["PL", "波蘭"],
  ["PF", "法屬玻利尼西亞"],
  ["PT", "葡萄牙"],
  ["PR", "波多黎各"],
  ["QA", "卡塔爾"],
  ["RO", "羅馬尼亞"],
  ["RU", "俄羅斯"],
  ["LC", "聖盧西亞"],
  ["VC", "聖文森特島"],
  ["SM", "聖馬力諾"],
  ["ST", "聖多美和普林西比"],
  ["SA", "沙特阿拉伯"],
  ["SN", "塞內加爾"],
  ["SC", "塞舌爾"],
  ["SL", "塞拉利昂"],
  ["SG", "新加坡"],
  ["SK", "斯洛伐克"],
  ["SI", "斯洛文尼亞"],
  ["SB", "所羅門群島"],
  ["SO", "索馬里"],
  ["ZA", "南非"],
  ["ES", "西班牙"],
  ["LK", "斯里蘭卡"],
  ["SD", "蘇丹"],
  ["SR", "蘇里南"],
  ["SZ", "斯威士蘭"],
  ["SE", "瑞典"],
  ["CH", "瑞士"],
  ["SY", "敘利亞"],
  ["TW", "台灣省"],
  ["TJ", "塔吉克斯坦"],
  ["TZ", "坦桑尼亞"],
  ["TH", "泰國"],
  ["TG", "多哥"],
  ["TO", "湯加"],
  ["TT", "特立尼達和多巴哥"],
  ["TN", "突尼斯"],
  ["TR", "土耳其"],
  ["TM", "土庫曼斯坦"],
  ["UG", "烏干達"],
  ["UA", "烏克蘭"],
  ["AE", "阿拉伯聯合酋長國"],
  ["GB", "英國"],
  ["US", "美國"],
  ["UY", "烏拉圭"],
  ["UZ", "烏茲別克斯坦"],
  ["VE", "委內瑞拉"],
  ["VN", "越南"],
  ["YE", "也門"],
  ["YU", "南斯拉夫"],
  ["ZW", "津巴布韋"],
  ["ZR", "扎伊爾"],
  ["ZM", "贊比亞"]
];
module.exports = {
  pickerData: pickerJson,
  geolocation
}  